backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "published", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", optional: true}
      - {label: "Is Draft?", name: "draft", widget: "boolean", default: false, optional: true}
      - {label: "Tags", name: "tags", widget: "list", optional: true}
      - {label: "Description", name: "description", widget: "text", optional: true}
      - label: "Cover Image"
        name: "coverImage"
        widget: "object"
        optional: true
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
